#!/usr/bin/env python3
"""
Check commits across all peak-flow GitHub repos in the last N hours
and save a markdown report.
"""
import os
import json
import urllib.request
import urllib.error
from datetime import datetime, timedelta, timezone

GITHUB_TOKEN = os.environ["GITHUB_TOKEN"]
ORG = os.environ.get("ORG", "peak-flow")
HOURS = int(os.environ.get("HOURS", "6"))

_headers = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def github_get(url):
    req = urllib.request.Request(url, headers=_headers)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read()), resp.headers
    except urllib.error.HTTPError as e:
        return None, None


def get_all_repos():
    repos = []
    page = 1
    while True:
        data, _ = github_get(
            f"https://api.github.com/orgs/{ORG}/repos?per_page=100&page={page}&sort=pushed"
        )
        if not data:
            break
        repos.extend(data)
        if len(data) < 100:
            break
        page += 1
    return repos


def count_commits(repo_name, since_iso):
    url = f"https://api.github.com/repos/{ORG}/{repo_name}/commits?since={since_iso}&per_page=100"
    data, _ = github_get(url)
    if data is None:
        return 0, False
    count = len(data)
    overflow = count == 100  # may have more than 100
    return count, overflow


def build_report(now, since, repos, active):
    lines = [
        "# Commit Activity Report",
        "",
        f"**Period:** Last {HOURS} hours  ",
        f"**From:** {since.strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**To:** {now.strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Organization:** [{ORG}](https://github.com/{ORG})  ",
        f"**Repos checked:** {len(repos)}  ",
        "",
    ]

    if not active:
        lines += [f"## No commits in the last {HOURS} hours", ""]
        return "\n".join(lines)

    total = sum(r["count"] for r in active)
    lines += [
        "## Summary",
        "",
        f"**{len(active)} repo(s)** with activity &nbsp;|&nbsp; **{total}+ commits** total",
        "",
        "| Repository | Language | Commits |",
        "|:-----------|:---------|--------:|",
    ]
    for r in active:
        suffix = "+" if r["overflow"] else ""
        lang = r["language"] or "—"
        lines.append(
            f"| [{r['name']}]({r['url']}) | {lang} | {r['count']}{suffix} |"
        )

    lines += ["", "---", f"*Generated by commit-tracker workflow*", ""]
    return "\n".join(lines)


def main():
    now = datetime.now(timezone.utc)
    since = now - timedelta(hours=HOURS)
    since_iso = since.strftime("%Y-%m-%dT%H:%M:%SZ")

    print(f"Checking commits since {since_iso} across {ORG} repos…")
    repos = get_all_repos()
    print(f"Found {len(repos)} repos")

    active = []
    for repo in repos:
        name = repo["name"]
        count, overflow = count_commits(name, since_iso)
        if count > 0:
            active.append(
                {
                    "name": name,
                    "count": count,
                    "overflow": overflow,
                    "url": repo["html_url"],
                    "language": repo.get("language"),
                }
            )
            print(f"  {name}: {count}{'+ ' if overflow else ' '} commits")

    active.sort(key=lambda x: x["count"], reverse=True)

    report = build_report(now, since, repos, active)

    os.makedirs("commit-reports", exist_ok=True)
    timestamp = now.strftime("%Y-%m-%d-%H00")
    path = f"commit-reports/{timestamp}.md"
    with open(path, "w") as f:
        f.write(report)

    print(f"\nReport saved → {path}")
    print(report)


if __name__ == "__main__":
    main()
