#!/usr/bin/env python3
"""
Queries GitHub for commits made across all accessible repos in the last 6 hours
and writes a summary markdown report to commit-report.md.
"""

import os
import sys
import requests
from datetime import datetime, timedelta, timezone

TOKEN = os.environ.get("GH_TOKEN")
if not TOKEN:
    print("Error: GH_TOKEN environment variable not set.", file=sys.stderr)
    sys.exit(1)

HEADERS = {
    "Authorization": f"token {TOKEN}",
    "Accept": "application/vnd.github.v3+json",
}

NOW = datetime.now(timezone.utc)
SINCE = (NOW - timedelta(hours=6)).isoformat()
SINCE_DT = NOW - timedelta(hours=6)


def paginate(url, params=None):
    results = []
    page = 1
    while True:
        p = {**(params or {}), "per_page": 100, "page": page}
        resp = requests.get(url, headers=HEADERS, params=p, timeout=30)
        if resp.status_code == 404:
            break
        resp.raise_for_status()
        data = resp.json()
        if not data:
            break
        results.extend(data)
        if len(data) < 100:
            break
        page += 1
    return results


def get_repos():
    # type=all includes private repos the token has access to
    return paginate("https://api.github.com/user/repos", {"type": "all", "sort": "pushed"})


def get_commit_count(full_name):
    """Return (count, list_of_authors) for commits since SINCE in this repo."""
    try:
        resp = requests.get(
            f"https://api.github.com/repos/{full_name}/commits",
            headers=HEADERS,
            params={"since": SINCE, "per_page": 100},
            timeout=30,
        )
        if resp.status_code in (409, 404, 403):
            # 409 = empty repo, 404 = no access, 403 = disabled
            return 0, []
        resp.raise_for_status()
        commits = resp.json()
        authors = list({
            c.get("commit", {}).get("author", {}).get("name", "unknown")
            for c in commits
        })
        return len(commits), sorted(authors)
    except Exception:
        return 0, []


def main():
    print("Fetching repositories...")
    repos = get_repos()
    print(f"Found {len(repos)} repositories. Checking commits since {SINCE}...")

    results = []
    total_commits = 0

    for i, repo in enumerate(repos, 1):
        full_name = repo["full_name"]
        pushed_at = repo.get("pushed_at") or ""

        # Skip repos that haven't been pushed to in the last 6 hours
        if pushed_at:
            try:
                pushed_dt = datetime.fromisoformat(pushed_at.replace("Z", "+00:00"))
                if pushed_dt < SINCE_DT:
                    continue
            except ValueError:
                pass

        count, authors = get_commit_count(full_name)
        if count > 0:
            results.append({
                "name": repo["name"],
                "full_name": full_name,
                "url": repo.get("html_url", ""),
                "commits": count,
                "authors": authors,
                "private": repo.get("private", False),
            })
            total_commits += count
            print(f"  [{i}/{len(repos)}] {full_name}: {count} commit(s)")
        else:
            print(f"  [{i}/{len(repos)}] {full_name}: 0")

    results.sort(key=lambda x: -x["commits"])

    report_time = NOW.strftime("%Y-%m-%d %H:%M UTC")
    since_time = SINCE_DT.strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# GitHub Commit Activity Report",
        "",
        f"**Report generated:** {report_time}  ",
        f"**Period covered:** {since_time} → {report_time}  ",
        f"**Total commits:** {total_commits}  ",
        f"**Active repos:** {len(results)} of {len(repos)} checked  ",
        "",
    ]

    if results:
        lines += [
            "## Repositories with Activity",
            "",
            "| Repository | Commits | Authors |",
            "|------------|--------:|---------|",
        ]
        for r in results:
            privacy = " 🔒" if r["private"] else ""
            authors_str = ", ".join(r["authors"]) if r["authors"] else "—"
            lines.append(
                f"| [{r['full_name']}]({r['url']}){privacy} | {r['commits']} | {authors_str} |"
            )
    else:
        lines.append("*No commits found in the last 6 hours.*")

    lines += [
        "",
        "---",
        f"*Auto-generated by [commit-tracker](.github/workflows/commit-tracker.yml)*",
    ]

    report_path = os.path.join(os.path.dirname(__file__), "..", "commit-report.md")
    with open(report_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nDone. {total_commits} commit(s) across {len(results)} repo(s).")
    print(f"Report written to commit-report.md")


if __name__ == "__main__":
    main()
